theme = "zen"
baseurl = ""
languageCode = "en-us"
title = "Uncompiled Source Code"
MetaDataFormat = "toml"
paginate = 10

[permalinks]
	post = "/blog/:year/:month/:day/:title/"
	about = "/:filename/"

[params]

gravatarHash = "9bef677be3cd588e6427102018d35f27"