theme = "zen"
baseurl = "http://shelan.org"
languageCode = "en-us"
title = "Uncompiled Source Code"
MetaDataFormat = "toml"
disqusShortname = "shelanblog" 
paginate = 10

[permalinks]
	tech = "/blog/:year/:month/:day/:title/"
	life = "/blog/:year/:month/:day/:title/"
	about = "/:filename/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "tech,life"

[params]
	gravatarHash = "9bef677be3cd588e6427102018d35f27"
	googleAnalytics = "UA-56325764-1"

highlight = "zenburn"